function [classNames,labelIDs] = getBrainCANDISegmentationLabels()
% Define segmentation class names and numeric label IDs

% Copyright 2022 The MathWorks, Inc.

classNames = ["background","leftCerebralWhiteMatter","leftCerebralCortex",...
    "leftLateralVentricle","leftInferiorLateralVentricle","leftCerebellumWhiteMatter",...
    "leftCerebellumCortex","leftThalamus","leftCaudate","leftPutamen","leftPallidum",...
    "thirdVentricle","fourthVentricle","brainStem","leftHippocampus","leftAmygdala",...
    "leftAccumbensArea","leftVentralDC","rightCerebralWhiteMatter","rightCerebralCortex",...
    "rightLateralVentricle","rightInferiorLateralVentricle","rightCerebellumWhiteMatter",...
    "rightCerebellumCortex","rightThalamus","rightCaudate","rightPutamen","rightPallidum",...
    "rightHippocampus","rightAmygdala","rightAccumbensArea","rightVentralDC"];

labelIDs = [0 2 3 4 5 7 8 10 11 12 13 14 15 16 17 18 26, ...
    28 41 42 43 44 46 47 49 50 51 52 53 54 58 60];
end