function [ ] = SAVE_fig_to_tikz( filename )
%UNTITLED Summary of this function goes here
% Detailed explanation goes here
matlab2tikz([filename,'.tex'],'width','\fw','height','\fh','extraaxisoptions',['title style={font=\small},'...
'xlabel style={font=\small},'...
'ylabel style={font=\small},',...
'legend style={font=\small},',...
'ticklabel style={font=\small}']);
fprintf('\n\nFINISHED!\n');
end
